# Generated by Django 2.0.1 on 2018-07-21 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParentsChild', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='being',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='miss',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='uid',
        ),
    ]
