# Generated by Django 2.0.1 on 2018-07-21 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParentsChild', '0004_auto_20180722_0249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='govnId',
            new_name='governid',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='phoneNumber',
            new_name='phonenum',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='ticketCount',
            new_name='ticketcount',
        ),
        migrations.AddField(
            model_name='ticket',
            name='schedule',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 22, 3, 47, 14, 501693)),
        ),
    ]
