# Generated by Django 2.0.1 on 2018-07-21 20:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParentsChild', '0005_auto_20180722_0347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='miss',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='schedule',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 22, 4, 28, 35, 754959)),
        ),
    ]
